//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimasService.LatWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LatitudeService.Coordenadas", Namespace="http://schemas.datacontract.org/2004/07/LatitudesService")]
    [System.SerializableAttribute()]
    public partial class LatitudeServiceCoordenadas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coordenadaXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coordenadaYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coordenadaX {
            get {
                return this.coordenadaXField;
            }
            set {
                if ((object.ReferenceEquals(this.coordenadaXField, value) != true)) {
                    this.coordenadaXField = value;
                    this.RaisePropertyChanged("coordenadaX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coordenadaY {
            get {
                return this.coordenadaYField;
            }
            set {
                if ((object.ReferenceEquals(this.coordenadaYField, value) != true)) {
                    this.coordenadaYField = value;
                    this.RaisePropertyChanged("coordenadaY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LatWS.ILatitudeService")]
    public interface ILatitudeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatitudeService/obtenerCoordenadas", ReplyAction="http://tempuri.org/ILatitudeService/obtenerCoordenadasResponse")]
        ClimasService.LatWS.LatitudeServiceCoordenadas obtenerCoordenadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatitudeService/obtenerCoordenadas", ReplyAction="http://tempuri.org/ILatitudeService/obtenerCoordenadasResponse")]
        System.Threading.Tasks.Task<ClimasService.LatWS.LatitudeServiceCoordenadas> obtenerCoordenadasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILatitudeServiceChannel : ClimasService.LatWS.ILatitudeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LatitudeServiceClient : System.ServiceModel.ClientBase<ClimasService.LatWS.ILatitudeService>, ClimasService.LatWS.ILatitudeService {
        
        public LatitudeServiceClient() {
        }
        
        public LatitudeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LatitudeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatitudeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatitudeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClimasService.LatWS.LatitudeServiceCoordenadas obtenerCoordenadas() {
            return base.Channel.obtenerCoordenadas();
        }
        
        public System.Threading.Tasks.Task<ClimasService.LatWS.LatitudeServiceCoordenadas> obtenerCoordenadasAsync() {
            return base.Channel.obtenerCoordenadasAsync();
        }
    }
}
