//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFQueueTests.ColasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColasWS.IColasService")]
    public interface IColasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColasService/ListarHabitacionesEnLimpieza", ReplyAction="http://tempuri.org/IColasService/ListarHabitacionesEnLimpiezaResponse")]
        string[] ListarHabitacionesEnLimpieza();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColasService/ListarHabitacionesEnLimpieza", ReplyAction="http://tempuri.org/IColasService/ListarHabitacionesEnLimpiezaResponse")]
        System.Threading.Tasks.Task<string[]> ListarHabitacionesEnLimpiezaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColasService/ListarHotelesNoValidados", ReplyAction="http://tempuri.org/IColasService/ListarHotelesNoValidadosResponse")]
        string[] ListarHotelesNoValidados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColasService/ListarHotelesNoValidados", ReplyAction="http://tempuri.org/IColasService/ListarHotelesNoValidadosResponse")]
        System.Threading.Tasks.Task<string[]> ListarHotelesNoValidadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IColasServiceChannel : WCFQueueTests.ColasWS.IColasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColasServiceClient : System.ServiceModel.ClientBase<WCFQueueTests.ColasWS.IColasService>, WCFQueueTests.ColasWS.IColasService {
        
        public ColasServiceClient() {
        }
        
        public ColasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ListarHabitacionesEnLimpieza() {
            return base.Channel.ListarHabitacionesEnLimpieza();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarHabitacionesEnLimpiezaAsync() {
            return base.Channel.ListarHabitacionesEnLimpiezaAsync();
        }
        
        public string[] ListarHotelesNoValidados() {
            return base.Channel.ListarHotelesNoValidados();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarHotelesNoValidadosAsync() {
            return base.Channel.ListarHotelesNoValidadosAsync();
        }
    }
}
