//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Business.ReniecService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WCFReniec.Dominio")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReniecService.IReniecService")]
    public interface IReniecService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecService/EsDniValido", ReplyAction="http://tempuri.org/IReniecService/EsDniValidoResponse")]
        bool EsDniValido(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecService/EsDniValido", ReplyAction="http://tempuri.org/IReniecService/EsDniValidoResponse")]
        System.Threading.Tasks.Task<bool> EsDniValidoAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecService/ObtenerPersonaPorDni", ReplyAction="http://tempuri.org/IReniecService/ObtenerPersonaPorDniResponse")]
        Booking.Business.ReniecService.Persona ObtenerPersonaPorDni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecService/ObtenerPersonaPorDni", ReplyAction="http://tempuri.org/IReniecService/ObtenerPersonaPorDniResponse")]
        System.Threading.Tasks.Task<Booking.Business.ReniecService.Persona> ObtenerPersonaPorDniAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReniecServiceChannel : Booking.Business.ReniecService.IReniecService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReniecServiceClient : System.ServiceModel.ClientBase<Booking.Business.ReniecService.IReniecService>, Booking.Business.ReniecService.IReniecService {
        
        public ReniecServiceClient() {
        }
        
        public ReniecServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReniecServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EsDniValido(string dni) {
            return base.Channel.EsDniValido(dni);
        }
        
        public System.Threading.Tasks.Task<bool> EsDniValidoAsync(string dni) {
            return base.Channel.EsDniValidoAsync(dni);
        }
        
        public Booking.Business.ReniecService.Persona ObtenerPersonaPorDni(string dni) {
            return base.Channel.ObtenerPersonaPorDni(dni);
        }
        
        public System.Threading.Tasks.Task<Booking.Business.ReniecService.Persona> ObtenerPersonaPorDniAsync(string dni) {
            return base.Channel.ObtenerPersonaPorDniAsync(dni);
        }
    }
}
