//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Business.BookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/BookService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadPersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniMiembroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCheckInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadPersonas {
            get {
                return this.CantidadPersonasField;
            }
            set {
                if ((this.CantidadPersonasField.Equals(value) != true)) {
                    this.CantidadPersonasField = value;
                    this.RaisePropertyChanged("CantidadPersonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoHabitacion {
            get {
                return this.CodigoHabitacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoHabitacionField, value) != true)) {
                    this.CodigoHabitacionField = value;
                    this.RaisePropertyChanged("CodigoHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoHotel {
            get {
                return this.CodigoHotelField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoHotelField, value) != true)) {
                    this.CodigoHotelField = value;
                    this.RaisePropertyChanged("CodigoHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniMiembro {
            get {
                return this.DniMiembroField;
            }
            set {
                if ((object.ReferenceEquals(this.DniMiembroField, value) != true)) {
                    this.DniMiembroField = value;
                    this.RaisePropertyChanged("DniMiembro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCheckIn {
            get {
                return this.FechaCheckInField;
            }
            set {
                if ((this.FechaCheckInField.Equals(value) != true)) {
                    this.FechaCheckInField = value;
                    this.RaisePropertyChanged("FechaCheckIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCheckOut {
            get {
                return this.FechaCheckOutField;
            }
            set {
                if ((this.FechaCheckOutField.Equals(value) != true)) {
                    this.FechaCheckOutField = value;
                    this.RaisePropertyChanged("FechaCheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroHabitacion {
            get {
                return this.NumeroHabitacionField;
            }
            set {
                if ((this.NumeroHabitacionField.Equals(value) != true)) {
                    this.NumeroHabitacionField = value;
                    this.RaisePropertyChanged("NumeroHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioHotel {
            get {
                return this.PrecioHotelField;
            }
            set {
                if ((this.PrecioHotelField.Equals(value) != true)) {
                    this.PrecioHotelField = value;
                    this.RaisePropertyChanged("PrecioHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservaId {
            get {
                return this.ReservaIdField;
            }
            set {
                if ((this.ReservaIdField.Equals(value) != true)) {
                    this.ReservaIdField = value;
                    this.RaisePropertyChanged("ReservaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookService.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RealizarReserva", ReplyAction="http://tempuri.org/IReservaService/RealizarReservaResponse")]
        Booking.Business.BookService.Reserva RealizarReserva(Booking.Business.BookService.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RealizarReserva", ReplyAction="http://tempuri.org/IReservaService/RealizarReservaResponse")]
        System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> RealizarReservaAsync(Booking.Business.BookService.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ModificarReserva", ReplyAction="http://tempuri.org/IReservaService/ModificarReservaResponse")]
        Booking.Business.BookService.Reserva ModificarReserva(Booking.Business.BookService.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ModificarReserva", ReplyAction="http://tempuri.org/IReservaService/ModificarReservaResponse")]
        System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> ModificarReservaAsync(Booking.Business.BookService.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaService/CancelarReservaResponse")]
        Booking.Business.BookService.Reserva CancelarReserva(int reservaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaService/CancelarReservaResponse")]
        System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> CancelarReservaAsync(int reservaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarReservasPorMiembro", ReplyAction="http://tempuri.org/IReservaService/ListarReservasPorMiembroResponse")]
        Booking.Business.BookService.Reserva[] ListarReservasPorMiembro(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarReservasPorMiembro", ReplyAction="http://tempuri.org/IReservaService/ListarReservasPorMiembroResponse")]
        System.Threading.Tasks.Task<Booking.Business.BookService.Reserva[]> ListarReservasPorMiembroAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : Booking.Business.BookService.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<Booking.Business.BookService.IReservaService>, Booking.Business.BookService.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Booking.Business.BookService.Reserva RealizarReserva(Booking.Business.BookService.Reserva reserva) {
            return base.Channel.RealizarReserva(reserva);
        }
        
        public System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> RealizarReservaAsync(Booking.Business.BookService.Reserva reserva) {
            return base.Channel.RealizarReservaAsync(reserva);
        }
        
        public Booking.Business.BookService.Reserva ModificarReserva(Booking.Business.BookService.Reserva reserva) {
            return base.Channel.ModificarReserva(reserva);
        }
        
        public System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> ModificarReservaAsync(Booking.Business.BookService.Reserva reserva) {
            return base.Channel.ModificarReservaAsync(reserva);
        }
        
        public Booking.Business.BookService.Reserva CancelarReserva(int reservaId) {
            return base.Channel.CancelarReserva(reservaId);
        }
        
        public System.Threading.Tasks.Task<Booking.Business.BookService.Reserva> CancelarReservaAsync(int reservaId) {
            return base.Channel.CancelarReservaAsync(reservaId);
        }
        
        public Booking.Business.BookService.Reserva[] ListarReservasPorMiembro(string dni) {
            return base.Channel.ListarReservasPorMiembro(dni);
        }
        
        public System.Threading.Tasks.Task<Booking.Business.BookService.Reserva[]> ListarReservasPorMiembroAsync(string dni) {
            return base.Channel.ListarReservasPorMiembroAsync(dni);
        }
    }
}
