//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfHotelTest.HotelesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotels", Namespace="http://schemas.datacontract.org/2004/07/WcfHotel.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstrellasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoImagen {
            get {
                return this.CodigoImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoImagenField, value) != true)) {
                    this.CodigoImagenField = value;
                    this.RaisePropertyChanged("CodigoImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estrellas {
            get {
                return this.EstrellasField;
            }
            set {
                if ((this.EstrellasField.Equals(value) != true)) {
                    this.EstrellasField = value;
                    this.RaisePropertyChanged("Estrellas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WcfHotel.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelesWS.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/CrearHotel", ReplyAction="http://tempuri.org/IHotelService/CrearHotelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfHotelTest.HotelesWS.RepetidoException), Action="http://tempuri.org/IHotelService/CrearHotelRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WcfHotel.Errores")]
        WcfHotelTest.HotelesWS.Hotels CrearHotel(WcfHotelTest.HotelesWS.Hotels hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/CrearHotel", ReplyAction="http://tempuri.org/IHotelService/CrearHotelResponse")]
        System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> CrearHotelAsync(WcfHotelTest.HotelesWS.Hotels hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ObtenerHotelPorCodigo", ReplyAction="http://tempuri.org/IHotelService/ObtenerHotelPorCodigoResponse")]
        WcfHotelTest.HotelesWS.Hotels ObtenerHotelPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ObtenerHotelPorCodigo", ReplyAction="http://tempuri.org/IHotelService/ObtenerHotelPorCodigoResponse")]
        System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> ObtenerHotelPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ModificarHotel", ReplyAction="http://tempuri.org/IHotelService/ModificarHotelResponse")]
        WcfHotelTest.HotelesWS.Hotels ModificarHotel(WcfHotelTest.HotelesWS.Hotels hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ModificarHotel", ReplyAction="http://tempuri.org/IHotelService/ModificarHotelResponse")]
        System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> ModificarHotelAsync(WcfHotelTest.HotelesWS.Hotels hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/EliminarHotel", ReplyAction="http://tempuri.org/IHotelService/EliminarHotelResponse")]
        int EliminarHotel(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/EliminarHotel", ReplyAction="http://tempuri.org/IHotelService/EliminarHotelResponse")]
        System.Threading.Tasks.Task<int> EliminarHotelAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ListarHoteles", ReplyAction="http://tempuri.org/IHotelService/ListarHotelesResponse")]
        WcfHotelTest.HotelesWS.Hotels[] ListarHoteles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/ListarHoteles", ReplyAction="http://tempuri.org/IHotelService/ListarHotelesResponse")]
        System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels[]> ListarHotelesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : WcfHotelTest.HotelesWS.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<WcfHotelTest.HotelesWS.IHotelService>, WcfHotelTest.HotelesWS.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfHotelTest.HotelesWS.Hotels CrearHotel(WcfHotelTest.HotelesWS.Hotels hotel) {
            return base.Channel.CrearHotel(hotel);
        }
        
        public System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> CrearHotelAsync(WcfHotelTest.HotelesWS.Hotels hotel) {
            return base.Channel.CrearHotelAsync(hotel);
        }
        
        public WcfHotelTest.HotelesWS.Hotels ObtenerHotelPorCodigo(string codigo) {
            return base.Channel.ObtenerHotelPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> ObtenerHotelPorCodigoAsync(string codigo) {
            return base.Channel.ObtenerHotelPorCodigoAsync(codigo);
        }
        
        public WcfHotelTest.HotelesWS.Hotels ModificarHotel(WcfHotelTest.HotelesWS.Hotels hotel) {
            return base.Channel.ModificarHotel(hotel);
        }
        
        public System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels> ModificarHotelAsync(WcfHotelTest.HotelesWS.Hotels hotel) {
            return base.Channel.ModificarHotelAsync(hotel);
        }
        
        public int EliminarHotel(string codigo) {
            return base.Channel.EliminarHotel(codigo);
        }
        
        public System.Threading.Tasks.Task<int> EliminarHotelAsync(string codigo) {
            return base.Channel.EliminarHotelAsync(codigo);
        }
        
        public WcfHotelTest.HotelesWS.Hotels[] ListarHoteles() {
            return base.Channel.ListarHoteles();
        }
        
        public System.Threading.Tasks.Task<WcfHotelTest.HotelesWS.Hotels[]> ListarHotelesAsync() {
            return base.Channel.ListarHotelesAsync();
        }
    }
}
